dtb-$(CONFIG_ARCH_PHYTIUM) += ft2004-devboard-d4-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += ft2004c-devboard-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += ft1500a-devboard-16c-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += ft2000plus-SR-devboard-64c-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += ft2000plus-MR-devboard-64c-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += ft2000ahk-devboard-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += d2000-devboard-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += ft2000ahke-devboard-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-demo-ddr4.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000q-demo-ddr4-local.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-demo-ddr4.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000d-demo-ddr4-local.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += e2000s-demo-ddr4.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
